// Auto-generated seed data from admin.html __PREASSIGNED_TABLES
// Each entry: guestName from the seating chart, mapped to the admin guest schema.
export const GUESTS: SeedGuest[] = [
  { first_name: "Ivana", last_name: "DePaz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Joaquin", last_name: "DePaz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Diana", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Vana", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Yasmini", last_name: "Matus", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Jean", last_name: "Harrison", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Sian", last_name: "DePaz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Mathew", last_name: "Preston", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Josue", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Maleek", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Devin", last_name: "Peyrefitte", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Yojalma", last_name: "Moleterno", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Carlitos", last_name: "Guest", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Jose", last_name: "DePaz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Mr. Mike Gonzalez", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Ingrid", last_name: "Gonzalez", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Aldo", last_name: "DePaz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Keisha", last_name: "Dwyer", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Ms. Marie DePaz", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Lily", last_name: "Lane", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Lucille", last_name: "Valladarez", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Norberto", last_name: "DePaz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "David", last_name: "DePaz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Vanessa", last_name: "Cuellar", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Javier", last_name: "DePaz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Miguel", last_name: "DePaz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Andre", last_name: "", spouse_name: "Adrian DePaz", guest_type: "couple", max_party: 2, attendance: "not_invited" },
  { first_name: "Olga", last_name: "Mendoza", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Xenia", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Sandino", last_name: "Mendoza", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Stephanie", last_name: "Hernandes", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Jahan", last_name: "Guerra", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Anthony", last_name: "Joseph", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Ceasar", last_name: "Quiroz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Zane", last_name: "Oliver", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "The Paniagua Family", last_name: "", spouse_name: "", guest_type: "family", max_party: 4, attendance: "not_invited" },
  { first_name: "Sonia", last_name: "Harris", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Floyd", last_name: "Haylock", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Carol", last_name: "Joiner", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Garry", last_name: "Flowers", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Mirianne", last_name: "Martinez", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Cindy", last_name: "Lisbey", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Oscar", last_name: "Lisbey", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Macarena", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Brian", last_name: "Silver", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Justin", last_name: "Mendoza", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Dave", last_name: "Dacak", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Shonda", last_name: "Matinez", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Marlon", last_name: "Andrews", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Maria Estella Recinos", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "karl", last_name: "Recinos", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Calos Dito Vega", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Emma", last_name: "Romero", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Destiny", last_name: "Wagner", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Vaneen", last_name: "Juan", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Krista", last_name: "Cruz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Earlyn", last_name: "Hutchinson", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Emil", last_name: "Pinelo", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Grandpa", last_name: "Pinelo", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Adrian", last_name: "Miller", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Maria Elena Heredia", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Luby", last_name: "Clemans", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Leticia", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Dijon", last_name: "McNab", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Hector", last_name: "Andrews", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Richard", last_name: "Cordova", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Brandon", last_name: "Guest", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Natasha", last_name: "Stuart", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Britney", last_name: "", spouse_name: "Camile Guy", guest_type: "couple", max_party: 2, attendance: "not_invited" },
  { first_name: "Shenny", last_name: "Boiton", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Ryan", last_name: "Smith", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Joseph", last_name: "", spouse_name: "Lorain Smith", guest_type: "couple", max_party: 2, attendance: "not_invited" },
  { first_name: "Carlos", last_name: "Habet", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "David", last_name: "Morales", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Angela", last_name: "kuylen", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "karina", last_name: "Farias", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Keidi", last_name: "Tejada", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Renee", last_name: "Pine", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "kylon", last_name: "Eiley", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Michel", last_name: "Chebat", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Geoffrey", last_name: "Waight", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Lawrence", last_name: "Thompson", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Miron", last_name: "Ortega", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Fabian", last_name: "Perez", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Wayne", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Oscar", last_name: "Trujeque", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Marcel", last_name: "Graniel", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "karim", last_name: "Espat", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Elvis", last_name: "Usher", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Fiona", last_name: "Rudon", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Ayden", last_name: "DePaz", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Lori", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Karine", last_name: "Cisneros", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Norine", last_name: "Haylock", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Mrs", last_name: "Veronica", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Estella", last_name: "Saucedo", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Dianne", last_name: "Haylock", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Miss Gilda", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
  { first_name: "Mrs Almira August", last_name: "", spouse_name: "", guest_type: "single", max_party: 1, attendance: "not_invited" },
];

type SeedGuest = {
  first_name: string;
  last_name: string;
  spouse_name: string;
  guest_type: string;
  max_party: number;
  attendance: string;
};
